name: Release Charm to Edge and Publish Libraries

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Quality Checks
    uses: canonical/observability/.github/workflows/_charm-quality-checks.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.6/stable
      parallelize-integration: true
      automatically-retry-hooks: true
      provider: machine
      charmcraft-channel: 3.x/stable
      charm-path: .
  release-charm:
    name: Release Charm and Libraries
    needs:
      - quality-checks
    uses: canonical/observability/.github/workflows/_charm-release.yaml@main
    secrets: inherit
    with:
      release-channel: "1.19/edge"
      charmcraft-channel: "3.x/stable"
  release-libs:
    name: Release any bumped charm library
    needs:
      - quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: charm

      - name: Release libraries
        run: |
          # Install Charmcraft
          sudo snap install charmcraft --classic --channel 3.x/stable
          cd $GITHUB_WORKSPACE/charm/
          # Get the charm name
          charm_name=$((yq .name metadata.yaml 2>/dev/null || yq .name charmcraft.yaml) | tr - _)
          if [[ $charm_name = "" ]]; then echo "Error: can't extract the charm name." && exit 1; fi
          # For each library belonging to the charm, publish it
          if [ -d lib/charms/$charm_name ]; then
            for lib in $(find lib/charms/$charm_name -type f | sed 's|lib/||' | sed 's/.py//' | sed 's|/|.|g'); do
              charmcraft publish-lib $lib
            done
          fi
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMHUB_TOKEN }}"
